# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cdncepwebapi:
    image: cdncepwebapi
    build:
      context: .
      dockerfile: src/cdncep-webapi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5184:5184
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
